name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Git Submodule Initialization
        run: git submodule update --init --recursive

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
#          CUSTOM_DOMAIN: docs.openquantumdesign.com
          CONFIG_FILE: ./mkdocs.yaml
#          EXTRA_PACKAGES: build-base
          REQUIREMENTS: ./docs/.requirements_docs.txt